
spring:
  datasource:
    url: "jdbc:sqlite://Users/helei/develop/ideaworkspace/depinbot/DepinBot/A_back/botData/db/auto_bot.db"

dubbo:
  application:
    name: bot-platform
    logger: slf4j
  registry:
#    id: zk-registry
#    address: zookeeper://127.0.0.1:2181
    id: nacos-registry
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isValid  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0    # 设置 1 为未删除
      logic-not-delete-value: 1 # 设置 0 为已删除
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    org:
      apache:
        dubbo: WARN
        zookeeper: WARN
server:
  port: 10010
