dubbo:
  protocol:
    name: dubbo
    port: 30800
  application:
    qos-enable: true
    qos-port: 30010
  registry:
    #    id: zk-registry
    #    address: zookeeper://127.0.0.1:2181
    id: nacos-registry
    address: nacos://localhost:8848
